### ISSUE TITLE
Rediscala v2.0 roadmap

### ISSUE THREAD

**Issue by etaty** [etaty/rediscala#209]
Roadmap for Rediscala v2.0

- [ ] split the code in module (core, protocol, commands, backends, cluster, ?)
  - [ ] publish command jars depending on Redis version?

- [ ] support multiple backends
  - [ ] akka (akka-io) (what Rediscala v1 is using) (we could use the typed actors?)
  - [ ] [Blaze](https://github.com/http4s/blaze)
  - [ ] [Colossus](https://github.com/tumblr/colossus) ?
  - [ ] scalajs (with a npm library) / scalanative (with [Hiredis](https://github.com/redis/hiredis))?

- [ ] Review and improve Redis cluster.
- [ ] Add missing Redis commands
- [ ] automate the release process (snapshot, and tagged versions)
- [ ] generate a doc website (with github pages)
- [ ] https://www.scala-exercises.org/

This is open to feedback and suggestions.
